export const items = [
  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 14",
    imgSrc: 'https://m.media-amazon.com/images/I/31gmva12KHL._SY445_SX342_QL70_FMwebp_.jpg',
    description: 'Apple iPhone 14 (128 GB) - Blue',
    price: '89999',
  },
  {
    id: 2,
    category: 'mobiles',
    title: "Google Pixel 8 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41OoZoSJE3L.jpg',
    description: 'Google Pixel 8 Pro (128GB) - Obsidian Black',
    price: '119999',
  },
  {
    id: 3,
    category: 'mobiles',
    title: "OnePlus 11R 5G",
    imgSrc: 'https://m.media-amazon.com/images/I/41etLpNZV6L._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'OnePlus 11R 5G | 16GB RAM, 256GB Storage',
    price: '49999',
  },
  {
    id: 4,
    category: 'mobiles',
    title: "Samsung Galaxy S23 Ultra",
    imgSrc: 'https://m.media-amazon.com/images/I/41GAnuY2-DL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Samsung Galaxy S23 Ultra | 12GB RAM, 256GB Storage, 200MP Camera',
    price: '124999',
  },
  {
    id: 5,
    category: 'mobiles',
    title: "Vivo X90 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41e8GQdzLwL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Vivo X90 Pro | 12GB RAM, 256GB Storage, Zeiss Camera',
    price: '84999',
  },
  {
    id: 6,
    category: 'laptops',
    title: "HP Spectre x360",
    imgSrc: 'https://m.media-amazon.com/images/I/41c6939ZqeL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'HP Spectre x360 Convertible 14-inch, Intel i7, 16GB RAM, 1TB SSD',
    price: '139999',
  },
  {
    id: 7,
    category: 'laptops',
    title: "ASUS ROG Zephyrus G14",
    imgSrc: 'https://m.media-amazon.com/images/I/51ambohiKcL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'ASUS ROG Zephyrus G14, AMD Ryzen 9, NVIDIA RTX 4060, 1TB SSD, 16GB RAM',
    price: '149999',
  },
  {
    id: 8,
    category: 'laptops',
    title: "Microsoft Surface Laptop Studio",
    imgSrc: 'https://m.media-amazon.com/images/I/41ilrzy-kVL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Microsoft Surface Laptop Studio (Intel Core i7, 32GB RAM, 1TB SSD)',
    price: '199999',
  },
  {
    id: 9,
    category: 'laptops',
    title: "Lenovo Legion Pro 5i",
    imgSrc: 'https://m.media-amazon.com/images/I/71wK6ao6Y8L._SX679_.jpg',
    description: 'Lenovo Legion Pro 5i | Intel Core i9, NVIDIA RTX 4070, 32GB RAM, 1TB SSD',
    price: '169999',
  },
  {
    id: 10,
    category: 'tablets',
    title: "Samsung Galaxy Tab S9 Ultra",
    imgSrc: 'https://m.media-amazon.com/images/I/41+KrYp-6wL._SY300_SX300_.jpg',
    description: 'Samsung Galaxy Tab S9 Ultra | 16GB RAM, 512GB Storage, 14.6-inch AMOLED',
    price: '139999',
  },
  {
    id: 11,
    category: 'tablets',
    title: "Realme Pad 2",
    imgSrc: 'https://m.media-amazon.com/images/I/41sGq2rbtqL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Realme Pad 2 (6GB RAM, 128GB ROM, 11.5-inch LCD)',
    price: '23999',
  },
  {
    id: 12,
    category: 'tablets',
    title: "Apple iPad Mini (6th Gen)",
    imgSrc: 'https://m.media-amazon.com/images/I/416wL+6mrNL._SX342_SY445_.jpg',
    description: 'Apple iPad Mini 6th Gen (8.3-inch, 64GB, Wi-Fi) - Space Gray',
    price: '59999',
  },
  {
    id: 13,
    category: 'mobiles',
    title: "Xiaomi 13 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41slvj1GZvL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Xiaomi 13 Pro | Snapdragon 8 Gen 2, 12GB RAM, 256GB Storage',
    price: '79999',
  },
  {
    id: 14,
    category: 'laptops',
    title: "Dell XPS 15",
    imgSrc: 'https://m.media-amazon.com/images/I/61MmNc4mRLL._SX679_.jpg',
    description: 'Dell XPS 15 | Intel Core i9, 32GB RAM, NVIDIA RTX 3050 Ti, 1TB SSD',
    price: '249999',
  },
  {
    id: 15,
    category: 'tablets',
    title: "Lenovo Tab P12",
    imgSrc: 'https://m.media-amazon.com/images/I/416q1ZPUjiL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Lenovo Tab P12 | 8GB RAM, 256GB Storage, 12.7-inch LCD',
    price: '39999',
  },
  {
    id: 16,
    category: 'mobiles',
    title: "Realme Narzo 60 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41BhXUYtDXL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Realme Narzo 60 Pro | 12GB RAM, 256GB Storage',
    price: '29999',
  },
  {
    id: 17,
    category: 'laptops',
    title: "Apple MacBook Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/618d5bS2lUL._SX679_.jpg',
    description: 'Apple MacBook Pro 16-inch | M2 Pro, 16GB RAM, 512GB SSD',
    price: '249999',
  },
  {
    id: 18,
    category: 'mobiles',
    title: "Oppo Find X2 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/91-2d0XeliL._SX679_.jpg',
    description: 'Oppo Find X2 Pro | 12GB RAM, 256GB Storage',
    price: '74999',
  },
  {
    id: 19,
    category: 'laptops',
    title: "Acer Predator Helios 16",
    imgSrc: 'https://m.media-amazon.com/images/I/41niYpmeEJL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Acer Predator Helios 16 | Intel i7, RTX 4060, 16GB RAM, 512GB SSD',
    price: '159999',
  },
  {
    id: 20,
    category: 'tablets',
    title: "Microsoft Surface Pro 9",
    imgSrc: 'https://m.media-amazon.com/images/I/41OXEf8SaHL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Microsoft Surface Pro 9 | 16GB RAM, 512GB SSD, 13-inch Touchscreen',
    price: '139999',
  },
  {
    id: 21,
    category: 'mobiles',
    title: "Samsung Galaxy Z Fold5",
    imgSrc: 'https://m.media-amazon.com/images/I/31lEj5JHUPL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Samsung Galaxy Z Fold5 | 12GB RAM, 256GB Storage, Foldable Display',
    price: '154999',
  },
  {
    id: 22,
    category: 'mobiles',
    title: "Nothing Phone (2)",
    imgSrc: 'https://m.media-amazon.com/images/I/51av4J53qTL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Nothing Phone (2) | 12GB RAM, 256GB Storage, Glyph Interface',
    price: '44999',
  },
  {
    id: 23,
    category: 'laptops',
    title: "ASUS TUF Gaming A15",
    imgSrc: 'https://m.media-amazon.com/images/I/61xBASwU+zL._SX679_.jpg',
    description: 'ASUS TUF Gaming A15 | 512GB SSD/NVIDIA GeForce RTX 2050',
    price: '199999',
  },
  {
    id: 24,
    category: 'tablets',
    title: "Amazon Fire HD 10",
    imgSrc: 'https://m.media-amazon.com/images/I/51yj9BpgEuL._SX679_.jpg',
    description: 'Amazon Fire HD 10 | 3GB RAM, 64GB Storage, 10.1-inch Full HD',
    price: '14999',
  },
  {
    id: 25,
    category: 'tablets',
    title: "Huawei MatePad Pro 12.6",
    imgSrc: 'https://m.media-amazon.com/images/I/41k2fGLD8OL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Huawei MatePad Pro | 12GB RAM, 512GB Storage, 12.6-inch OLED Display',
    price: '69999',
  },
  {
    id: 26,
    category: 'laptops',
    title: "HP Envy x360",
    imgSrc: 'https://m.media-amazon.com/images/I/41rH45mIbKL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'HP Envy x360 | Intel Core i7, 16GB RAM, 512GB SSD, Convertible Laptop',
    price: '99999',
  },
  {
    id: 27,
    category: 'mobiles',
    title: "Realme GT 6T 5G",
    imgSrc: 'https://m.media-amazon.com/images/I/41Pi7EciJqL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Realme GT 6T 5G | 16GB RAM, 256GB Storage, 240W Fast Charging',
    price: '37999',
  },
  {
    id: 28,
    category: 'laptops',
    title: "Apple MacBook Air 15",
    imgSrc: 'https://m.media-amazon.com/images/I/41PlpJ2I5bL._SY445_SX342_QL70_FMwebp_.jpg',
    description: 'Apple MacBook Air 15-inch | M2, 8GB RAM, 256GB SSD',
    price: '134999',
  },
  {
    id: 29,
    category: 'mobiles',
    title: "iQOO Neo 9 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41m-C1HHkIL._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'iQOO Neo 9 Pro | 12GB RAM, 256GB Storage, Snapdragon 8+ Gen 1',
    price: '34999',
  },
  {
    id: 30,
    category: 'tablets',
    title: "Xiaomi Pad 6 Pro",
    imgSrc: 'https://m.media-amazon.com/images/I/41nIyVgOb-L._SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Xiaomi Pad 6 Pro | 12GB RAM, 512GB Storage, 11-inch LCD, Snapdragon 8+ Gen 1',
    price: '49999',
  },
];
